openapi: 3.0.0
info:
  title: Plates API
  description: API for Plates Backend
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /auth/me:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${auth_me_arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        timeoutInMillis: 20000
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
      security:
        - CognitoUserPoolAuthorizer: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string

  /library:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${library_get_arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        timeoutInMillis: 20000
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
      security:
        - CognitoUserPoolAuthorizer: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkoutMetadata'
    post:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${library_post_arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        timeoutInMillis: 20000
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
      security:
        - CognitoUserPoolAuthorizer: [ ]
      parameters:
        - in: path
          name: templateId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkoutTemplateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTemplate'
  /library/{templateId}:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${library_item_get_arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        timeoutInMillis: 20000
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
      security:
        - CognitoUserPoolAuthorizer: [ ]
      parameters:
        - in: path
          name: templateId
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTemplate'

components:
  securitySchemes:
    CognitoUserPoolAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
          - "${cognito_user_pool_arn}"
        type: "cognito_user_pools"
  schemas:
    CreateWorkoutTemplateRequest:
      type: object
      properties:
        name:
          type: string
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/TemplateExercise'

    WorkoutMetadata:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        version:
          type: integer
    WorkoutTemplate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        version:
          type: integer
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/TemplateExercise'
    TemplateExercise:
      type: object
      properties:
        name:
          type: string
        sets:
          type: integer
        reps:
          type: integer
        weight:
          type: integer
        rest:
          type: integer