openapi: 3.0.0
info:
  title: Plates API
  description: API for Plates Backend
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /library:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkoutMetadata'
  /library/{templateId}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTemplate'
    post:
      parameters:
        - in: path
          name: templateId
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutTemplate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutTemplate'

components:
  schemas:
    WorkoutMetadata:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        version:
          type: integer
    WorkoutTemplate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        version:
          type: integer
        exercises:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              sets:
                type: integer
              reps:
                type: integer
              weight:
                type: integer
              rest:
                type: integer